### ISSUE TITLE
Team Considerations of a new Guideline

### ISSUE THREAD

**Issue by DannyFGitHub** [ablewitt/team_13-app#5]
Priority: Medium

Guideline is not clear on what we should do with variable name cases and method name cases of acronyms.
E.g.
UI - all upper case as its important the reader should not be confused as to whether the I (i) is an l (L)
ui - all lower case, because its interpreted as one word
uI - because it represents two different words using camelCasing

Let's discuss this issue and come up with a resolution.

**Comment by ablewitt** [comment]
Is the acronym to be treated as 1 word or multiple 1 letter words?

**Comment by ablewitt** [comment]
I propose acronyms used for variables/method are to be lower case when used by themselves or when at the start of a variable/method name, other cases (class and enum names) the acronym must be all uppercase.

This should stop the use of mixed case when the acronym is used.

**Comment by danielnetwork** [comment]
This has been resolved by incorporating a new guideline, guideline 12 into our Iteration 1 and Iteration 2 plans.

> Acronyms used for variables/method are to be lower case when used by themselves or when at the start of a variable/method name, other cases (class and enum names) the acronym must be all uppercase
